name: React Testing and Deploying

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: yarn install
  deploy:
    name: Deploying
    runs-on: ubuntu-20.04
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_AWS_SERVER_IP}}
          username: ${{ secrets.SSH_SERVER_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          script: |
            cd ~/.scripts
            ./docker-deploy.sh
